// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode'; // This gives access to: editor events, documents, commands, windows, workspace, APIs
import { startActivityTracking, registerPendingAiInsertion, onAISuggestionAccepted } from './activityTracker';
import {isCopilotActive} from './detectCopilot';
import {startSessionTracking} from './sessionTracker';
import {startErrorTracking} from './errorTracking';
import { registerAutomaticRuntimeTracker } from './runtimeTracker';
import {initTelemetry, getLogFilePath, getVerificationBufferFilePath } from './telemetry';
import { startCopilotOtelTracking } from './copilotOtelTracker';
import path from 'path';

// This method is called when your extension is activated
// Your extension is activated the very first time the command is executed

let activeSession: any; // Variable to hold the active session tracking instance, allowing it to be accessed and ended when the extension is deactivated

export function activate(context: vscode.ExtensionContext) {
	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "codexlog" is now active!');

	startCopilotOtelTracking(context);

	initTelemetry(context.globalStorageUri.fsPath); // Initialize telemetry logging, setting up the log file path and ensuring necessary directories exist, using the extension's global storage path
	console.log("Telemetry initialized at:", getLogFilePath()); // Log the path to the telemetry log file for debugging purposes, allowing developers to easily locate and inspect the log file generated by the extension
	activeSession = startSessionTracking(context); // Start tracking the user's session, including workspace activity and idle time, passing the extension context for proper resource management
	const tracker = startActivityTracking(context); // Start tracking user activity and logging telemetry data, passing the extension context for proper resource management

	startErrorTracking(context); // Start tracking linter/compiler errors for opened files, logging diagnostics on save, passing the extension context for proper resource management

	// Registering a new command to run user code and track runtime errors, allowing users to execute their code and capture any runtime stack traces for analysis
	registerAutomaticRuntimeTracker(context);

	// Registering a new command to log telemetry data, allowing users to view a summary of their editing activity
	const summaryCommand = vscode.commands.registerCommand('codexlog.logTelemetry', () => {
		const stats = tracker.getStats(); // receive the current stats from the activity tracker, which includes total edits and saves
		vscode.window.showInformationMessage(`Total Edits: ${stats.totalEdits}, Total Saves: ${stats.totalSaves}`); // Display the telemetry summary to the user in an information message box
	});
	context.subscriptions.push(summaryCommand); // This ensures that the command is disposed of when the extension is deactivated

	// detecting if GitHub Copilot is active in the user's VSCode environment, allowing the extension to adjust its behavior accordingly
	const copilotStatus = isCopilotActive();
	console.log('GitHub Copilot Status:', copilotStatus);

	// Rregister a command to open it directly in VS Code
	const openLogCommand = vscode.commands.registerCommand('codexlog.openLog', () => {
		const logPath = getLogFilePath();
		if (!logPath) {
			vscode.window.showErrorMessage('Telemetry log not initialised yet.');
			return;
		}
		vscode.workspace.openTextDocument(logPath).then(doc => {
			vscode.window.showTextDocument(doc);
		});
	});
	context.subscriptions.push(openLogCommand);

	const openVerificationBufferCommand = vscode.commands.registerCommand('codexlog.openVerificationBuffer', () => {
		const logPath = getVerificationBufferFilePath();
		if (!logPath) {
			vscode.window.showErrorMessage('Verification buffer log not initialised yet.');
			return;
		}
		vscode.workspace.openTextDocument(logPath).then(doc => {
			vscode.window.showTextDocument(doc);
		});
	});
	context.subscriptions.push(openVerificationBufferCommand);

const interceptGhostText = vscode.commands.registerCommand('codexlog.acceptInlineSuggestion', async () => {
        const editor = vscode.window.activeTextEditor;
        const fileFallback = editor ? vscode.workspace.asRelativePath(editor.document.uri, false) : 'unknown';
        const languageFallback = editor?.document.languageId ?? 'unknown';
        const startLine = editor?.selection.active.line ?? 0;

        // 1. Tell your synchronous document listener that an AI edit is imminent
        registerPendingAiInsertion();

        // 2. Force VS Code to accept the ghost text
        await vscode.commands.executeCommand('editor.action.inlineSuggest.commit');

        // 3. Route it through your existing AI acceptance logic.
        // We pass an empty string for text and a hardcoded ID for OTel because 
        // onAISuggestionAccepted will automatically claim the true text and 
        // counts from the paste reconciliation queue.
        onAISuggestionAccepted(
            fileFallback, 
            languageFallback, 
            "", // The queue will overwrite this with the real inserted text
            startLine, 
            "ghost-text-inline" // Custom ID to distinguish from OTel spans
        );
    });

    context.subscriptions.push(interceptGhostText);
}

// This method is called when your extension is deactivated
export function deactivate() {
	activeSession?.endSession(); // Call the endSession function to log the final session summary when the extension is deactivated
}
